# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
  pull_request:
    branches: [main, develop]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ==================== CODE QUALITY ====================
  
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install black isort flake8 mypy
          pip install -r requirements.txt

      - name: Run Black
        run: black --check app/

      - name: Run isort
        run: isort --check-only app/

      - name: Run Flake8
        run: flake8 app/ --max-line-length=120 --ignore=E203,W503

      - name: Run MyPy
        run: mypy app/ --ignore-missing-imports

  # ==================== SECURITY SCANNING ====================
  
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  # ==================== TESTING ====================
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: chatbot
          POSTGRES_PASSWORD: test
          POSTGRES_DB: chatbot_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run unit tests
        env:
          DATABASE_URL: postgresql+asyncpg://chatbot:test@localhost:5432/chatbot_test
          REDIS_URL: redis://localhost:6379/0
          TESTING: true
        run: |
          pytest tests/unit -v --cov=app --cov-report=xml --cov-report=term

      - name: Run integration tests
        env:
          DATABASE_URL: postgresql+asyncpg://chatbot:test@localhost:5432/chatbot_test
          REDIS_URL: redis://localhost:6379/0
          TESTING: true
        run: |
          pytest tests/integration -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  # ==================== BUILD & PUSH ====================
  
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ==================== DEPLOY TO STAGING ====================
  
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.chatbot.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > ~/.kube/config

      - name: Deploy to staging
        run: |
          kubectl set image deployment/chatbot-api \
            api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop \
            -n mcp-chatbot-staging
          kubectl rollout status deployment/chatbot-api -n mcp-chatbot-staging

      - name: Run smoke tests
        run: |
          curl -f https://staging.chatbot.com/health || exit 1
          curl -f https://staging.chatbot.com/api/v1/health || exit 1

  # ==================== DEPLOY TO PRODUCTION ====================
  
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: production
      url: https://api.chatbot.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_PROD }}" | base64 -d > ~/.kube/config

      - name: Deploy to production
        run: |
          kubectl set image deployment/chatbot-api \
            api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            -n mcp-chatbot
          kubectl rollout status deployment/chatbot-api -n mcp-chatbot --timeout=10m

      - name: Run smoke tests
        run: |
          curl -f https://api.chatbot.com/health || exit 1
          curl -f https://api.chatbot.com/api/v1/health || exit 1

      - name: Notify deployment
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          text: |
            Production deployment ${{ job.status }}
            Version: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

  # ==================== DATABASE MIGRATIONS ====================
  
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install alembic asyncpg

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          alembic upgrade head

# ==================== NOTES ====================
#
# Required Secrets:
# - GITHUB_TOKEN (automatically provided)
# - KUBE_CONFIG_STAGING (base64 encoded kubeconfig)
# - KUBE_CONFIG_PROD (base64 encoded kubeconfig)
# - PROD_DATABASE_URL
# - SLACK_WEBHOOK (optional, for notifications)
#
# Setup:
# 1. Enable GitHub Actions in repository settings
# 2. Add secrets in Settings > Secrets and variables > Actions
# 3. Configure environments (staging, production) with protection rules
# 4. Set up branch protection for main branch
#
# Deployment Flow:
# - Push to develop → Deploy to staging
# - Create tag v1.0.0 → Deploy to production
# - Pull requests → Run tests only
#
# Manual Deployment:
# - Go to Actions tab
# - Select workflow
# - Click "Run workflow"
